// app/components/Skills.tsx
const skills = [
  { skill: 'Javascript' },
  { skill: 'Python' },
  { skill: 'C++' },
  { skill: 'Django Rest Framework' },
  { skill: 'GraphQL' },
  { skill: 'VueJS' },
  { skill: 'NuxtJS' },
  { skill: 'ReactJS' },
  { skill: 'NumPy' },
  { skill: 'Pandas' },
  { skill: 'Matplotlib' },
  { skill: 'TensorFlow' },
  { skill: 'PyTorch' },
  { skill: 'Postgres' },
  { skill: 'AWS' },
  { skill: 'Docker' },
  { skill: 'Adobe XD' },
  { skill: 'Figma' },
  { skill: 'Django' },
  { skill: 'Solidworks' },
]

import React from 'react'

export default function Skills() {
  return (
    <div className="my-10 md:mx-40 mx-3">
      <div>
        <h1 className="text-4xl font-black text-center text-primary py-5">Skills</h1>
        {skills.map(({skill}) => (
          <button key={skill} className="btn btn-primary btn-outline normal-case text-xl m-1">{skill}</button>
        ))}
      </div>
    </div>
  )
}

// components/Skills.vue
<script setup>

const skills = [
  { name: 'Javascript' },
  { name: 'Python' },
  { name: 'C++' },
  { name: 'Django' },
  { name: 'Django Rest Framework' },
  { name: 'GraphQL' },
  { name: 'VueJS' },
  { name: 'NuxtJS' },
  { name: 'ReactJS' },
  { name: 'NumPy' },
  { name: 'Pandas' },
  { name: 'Matplotlib' },
  { name: 'TensorFlow' },
  { name: 'PyTorch' },
  { name: 'Postgres' },
  { name: 'AWS' },
  { name: 'Docker' },
  { name: 'Adobe XD' },
  { name: 'Figma' },
  { name: 'Solidworks' },
]

</script>

<template>
    <div class="md:container md:mx-auto py-16">
        <h1 class="text-3xl text-center font-bold text-primary">Skills</h1>
        <div class="px-10">
            <button
                v-for="skill in skills"
                :key="skill.name"
                class="btn btn-outline btn-primary m-1"
            >
                {{ skill.name }}
            </button>
        </div>
    </div>
</template>
